# Generated by Django 5.2.9 on 2025-12-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issued_by', models.CharField(max_length=255)),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
    ]
